BUILD_DIR ?= build
KEYRING_TARGET_DIR ?= $(PREFIX)/share/pacman/keyrings/
KEYRING_PREFIX=fzt-repo
KEYRING_FILE=$(BUILD_DIR)/$(KEYRING_PREFIX).gpg
KEYRING_REVOKED_FILE=$(BUILD_DIR)/$(KEYRING_PREFIX)-revoked
KEYRING_TRUSTED_FILE=$(BUILD_DIR)/$(KEYRING_PREFIX)-trusted

SOURCES=$(shell find keyring -type f)

build: $(SOURCES)
	./build.sh $(BUILD_DIR) $(KEYRING_FILE) $(KEYRING_TRUSTED_FILE) $(KEYRING_REVOKED_FILE) $(SOURCES)

install:
	install -vDm 644 $(KEYRING_FILE) $(KEYRING_REVOKED_FILE) $(KEYRING_TRUSTED_FILE) -t $(DESTDIR)$(KEYRING_TARGET_DIR)

check:


.PHONY: install check
